// Sirve /icon-512.png con el logotipo de Factura Mis Gastos embebido.
// Solucion temporal libre de binarios: reemplazar por el archivo real en
// public/ cuando se pueda hacer push de binarios (ver PR #74).
import { NextResponse } from "next/server";

export const dynamic = "force-static";

const DATA_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAQ7ElEQVR4nO3d3ZkUtxaG0cYPIRADkREWkREDOfS5GDjATP9Udamk" +
  "LX1rXRtTMy7t/aIe25+u1+v1AgBE+W/0AwAA/QkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBA" +
  "AgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAA" +
  "CCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAA" +
  "AIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACDQ59EPABzz9dvP7r/nj+9fuv+eQFufrtfrdfRDAB+NWOytCQWoSwDAQCss" +
  "+VeJAxhLAEAHyYt+L2EAfQgAaMyyb08UQHsCAA6y8PsTBHCcAICdLPx6BAHsJwDgCQt/PoIAnhMAcIOlvw4xALcJAPjF0l+fGIA/" +
  "BADRLP1cYoB0AoA4lj7viQESCQAiWPpsJQZIIQBYlqXPUWKAlQkAlmPx05oQYEUCgGVY/JxNCLASAcDULH1GEQPMTgAwJYufKoQA" +
  "sxIATMXipyohwGwEAFOw+JmFEGAWAoDSLH5mJQSoTgBQksXPKoQAVQkASrH4WZUQoBoBQAkWPymEAFUIAIay+EklBBhNADCExQ9v" +
  "hACjCAC6svjhNiFAb/+NfgByWP5wn/NBb24AOJ3BBvu4DaAHAcBpLH44RghwJh8BcArLH45zjjiTGwCaMrDgHG4DaM0NAM1Y/nAe" +
  "54vW3ABwmMEEfbkNoAU3ABxi+UN/zh0tuAHgJQYQ1OA2gFe5AWA3yx/qcB55lRsANjNooDa3AezhBoBNLH+ozzllDwHAU4YKzMN5" +
  "ZSsfAXCXQQJz85EAj7gB4CbLH+bnHPOIAOADQwPW4Txzj48A+D+DAtbmIwH+5gaAy+Vi+UMC55y/CQAMBQjivPObAAhnGEAe557L" +
  "xc8AxDIAgMvFzwUkcwMQyPIHfjMPcgmAMA478J65kEkABHHIgXvMhzwCIITDDTxjTmQRAAEcamAr8yKHAFicwwzsZW5kEAALc4iB" +
  "V5kf6xMAi3J4gaPMkbUJgAU5tEAr5sm6BMBiHFagNXNlTQJgIQ4pcBbzZT0CYBEOJ3A2c2YtAmABDiXQi3mzDgEwOYcR6M3cWYMA" +
  "mJhDCIxi/sxPAEzK4QNGM4fmJgAm5NABVZhH8xIAk3HYgGrMpTkJgIk4ZEBV5tN8BMAkHC6gOnNqLgJgAg4VMAvzah4CoDiHCZiN" +
  "uTUHAVCYQwTMyvyqTwAAQCABUJR6BmZnjtUmAApyaIBVmGd1CYBiHBZgNeZaTQKgEIcEWJX5Vo8AAIBAAqAIdQyszpyrRQAU4FAA" +
  "Kcy7OgTAYA4DkMbcq0EAAEAgATCQCgZSmX/jCYBBvPxAOnNwLAEwgJce4I15OI4AAIBAAqAztQvwL3NxDAHQkZcc4DbzsT8BAACB" +
  "BEAn6hbgMXOyLwHQgZcaYBvzsh8BAACBBMDJ1CzAPuZmHwLgRF5igNeYn+cTAAAQSACcRL0CHGOOnksAnMBLC9CGeXoeAQAAgQRA" +
  "Y2oVoC1z9RwCAAACfbper9fRD7EKldrXj+9fRj8CPGQmtOXMt+UGoBEHHeBc5mxbAgAAAgmABlQpQB/mbTsCAAACCYCD1ChAX+Zu" +
  "GwIAAAIJgANUKMAY5u9xAgAAAgmAF6lPgLHM4WMEAAAEEgAvUJ0ANZjHrxMAABBIAOykNgFqMZdfIwAAIJAA2EFlAtRkPu8nAAAg" +
  "kADYSF0C1GZO7yMAACCQANhAVQLMwbzeTgAAQCAB8ISaBJiLub2NAACAQAIAAAIJgAdcIwHMyfx+TgAAQCABcId6BJibOf6YAACA" +
  "QALgBtUIsAbz/D4BAACBBAAABBIA77guAliLuX6bAACAQAIAAAIJgL+4JgJYk/n+kQAAgEACAAACCYBfXA8BrM2c/5cAAIBAAgAA" +
  "AgmAi2shgBTm/R8CAAACCQAACBQfAK6DALKY+2/iAwAAEn0e/QCQzJ9EgFGibwAMX4BM5n94AABAKgEAAIEEAAAEig0An/8AZEvf" +
  "A7EBAADJBAAABBIAABAoMgDSP/cB4E3yPogMAABIJwAAIJAAAIBAcQGQ/HkPAB+l7oW4AAAABAAARBIAABBIAABAoKgASP1BDwAe" +
  "S9wPUQEAALwRAAAQSAAAQCABAACBBAAABIoJgMSf8ARgu7Q9ERMAAMAfAgAAAgkAAAgkAAAgkAAAgEACAAACRQRA2r/aAcBrkvZF" +
  "RAAAAP8SAAAQSAAAQCABAACBBAAABBIAABBIAABAoM+jHwCS/fj+ZfQjlJb072RDb24AACDQ8gHgTxAA7JGyN5YPAADgIwEAAIEE" +
  "AAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQ" +
  "SAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEGj5APjx/cvoRwBgIil7Y/kAAKgoZclQ1+fRDwDJvn77OfoRGOD38v/x" +
  "/Yt3gGHcAAB09P5P/m4CGEUAAHRyb9mLAEYQAAAdPFvyIoDeBADAybYudxFATwIA4ER7l7oIoBcBAHCSV5e5CKAHAQBwgqNLXARw" +
  "togAcJCAnlrNHLOrv6TveUQAAPTSeoEkLST6EgAAjZy1rEUAZxAAAA2cvaRFAK0JAICDei1nEUBLAgDggN5LWQTQigAAeNGoZSwC" +
  "aCEmABwYoKXRM2X077+itO9pTAAAtFJhUXz99nP0IzA5AQCwg+XPKgQAwEaWPysRAAAbWP6sRgAAPGH5s6KoAKhwiIG5VJgblv/5" +
  "Kvxz7i0qAAD2qLAULH/OIgAAbrD8WZ0AAHjH8ieBAAD4i+VPirgAqHC4gZoqzAfLv78K/9xHiAsAgFsqLAHLn54EABDP8ieRAACi" +
  "Wf6kigyACgceGK/CLLD8x6rwDowSGQAAFQa/5c9IAgCIY/mDAADCWP7wJjYAKgwBoK8K597yr6PC+zBSbAAAWSoMe8ufSgQAsDzL" +
  "Hz4SAMDSLH+4LToAKgwG4DwVzrjlX1OFd2O06AAA7pt9QFZ4fsufygQA8MHv5Vlhib6iwnNb/lQXHwAVBgVU8v5MzHZGKjyv5V9b" +
  "hXekgvgAAP64NxhnGZgVntPyZxYCALhcLs+XZ4Xl+kiF57P8mYkAuNQYHDDS1jNQ9axUeC7Lfw4V3pUqBACE2zsQqw3QCs9j+TMj" +
  "AQDBXl2eFZbu5VLjOSx/ZiUAfqkwSKCno+/86DMz+ve/XCz/2VR4ZyoRABCo1SAcNVArDHLLn9kJAAjTenn2XsaWP7QhAP5SYbDA" +
  "mc56x3udnQpn1PKfU4V3pxoBACHOHoCz//23sPxZiQCAALP/Cd3yh/YEwDsVBg20NPtn9BXOpOU/twrvUEUCABY2+0/pVxjclj+r" +
  "EgCwqNHLc/b/zsDlYvmzNgFwQ4XBA0dVWF4z/5cGK3z/OK7Cu1SVAICFVVhiM/6/Bip83+BsAuCOCkMIWqiwzGb6vw1W+H7RRoX3" +
  "qTIBAAEqLLVnw7jCsK7wfYJeBMADFQYStFJhud07UxXOWoXvD+1UeKeqEwAQpMKSez+YKwzqCt8X6E0AQJgKy+730rf8YRwB8ESF" +
  "AQWtVVh6Fc5Whe8D7VV4t2YgACBU+vJL//pBAGygJllV6hJM/boTmNfbCQAIl7YM075euEcAbKQqWVnKUkz5OlOZ0/sIAOByuay/" +
  "HFf/+mAvAbCDumR1qy7JVb8u/jCf9xMAwD9WW5arfT3QigDYSWWSYJWlucrXwWPm8msEAHDT7Mtz9ueHswmAF6hNUsy6RGd9bvYz" +
  "j18nAICHZlumsz0vjCIAXqQ6STLLUp3lOWnDHD5GAACbVF+u1Z8PqhEAB6hP0lRdslWfi/OYv8cJAGCXasu22vPALATAQSqURFWW" +
  "bpXnoC9ztw0BALzk6PId/eshnQBoQI2S6tUl/PvXHf315DFv2xEAwCF7l/H7v/7orwdeIwAaUaUk27qU7/11R389GczZtj5dr9fr" +
  "6IdYiQFFskcDesvZOPrrWZfl354bAKCZs/6Eb/lDewKgMZVKutaf8Vv+mKvnEABAc61+yt/yh/P4GYCTGFwAx/nT/3ncAJzESwtw" +
  "jDl6LgEAAIEEwInUK8BrzM/zCYCTeYkB9jE3+xAAABBIAHSgZgG2MS/7EQCdeKkBHjMn+xIAABBIAHSkbgFuMx/7EwCdeckB/mUu" +
  "jiEAACCQABhA7QK8MQ/HEQCDeOmBdObgWAJgIC8/kMr8G08AAEAgATCYCgbSmHs1CIACHAYghXlXhwAowqEAVmfO1SIAACCQAChE" +
  "HQOrMt/qEQDFOCTAasy1mgRAQQ4LsArzrC4BUJRDA8zOHKtNAABAIAFQmHoGZmV+1ScAinOIgNmYW3MQABNwmIBZmFfzEACTcKiA" +
  "6sypuQiAiThcQFXm03wEwGQcMqAac2lOAmBCDhtQhXk0LwEwKYcOGM0cmpsAmJjDB4xi/sxPAEzOIQR6M3fWIAAW4DACvZg36xAA" +
  "i3AogbOZM2sRAAtxOIGzmC/rEQCLcUiB1syVNQmABTmsQCvmyboEwKIcWuAoc2RtAmBhDi/wKvNjfQJgcQ4xsJe5kUEABHCYga3M" +
  "ixwCIIRDDTxjTmQRAEEcbuAe8yGPAAjjkAPvmQuZBEAghx34zTzI9el6vV5HPwTjfP32c/QjAANY/LgBCGcIQB7nnstFAHAxDCCJ" +
  "885vAoDL5WIoQALnnL/5GQA+8HMBsBaLn1vcAPCBYQHrcJ65RwBwk6EB83OOecRHADzlIwGYi8XPFm4AeMowgXk4r2wlANjEUIH6" +
  "nFP28BEAu/lIAGqx+HmFGwB2M2ygDueRV7kB4BC3ATCGxc9RbgA4xBCC/pw7WnADQDNuA+BcFj8tuQGgGcMJzuN80ZobAE7hNgDa" +
  "sPg5ixsATmFowXHOEWdyA8Dp3AbAPhY/PQgAuhEC8JjFT08+AqAbww3ucz7ozQ0AQ7gNgDcWP6MIAIYSAqSy+BlNAFCCECCFxU8V" +
  "AoBShACrsvipRgBQkhBgFRY/VQkAShMCzMripzoBwBSEALOw+JmFAGAqQoCqLH5mIwCYkhCgCoufWQkApiYEGMXiZ3YCgGWIAc5m" +
  "6bMSAcByhACtWfysSACwLCHAURY/KxMARBADbGXpk0IAEEcM8J6lTyIBQDQxkMvSJ50AgF/EwPosffhDAMANYmAdlj7cJgDgCTEw" +
  "H0sfnhMAsJMgqMfCh/0EABwkCPqz8OE4AQCNCYL2LHxoTwBAB6JgO8se+hAAMFByGFj0MJYAgKJWiANLHuoSADC5EaFgscP8BAAA" +
  "BPpv9AMAAP0JAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAA" +
  "AgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQA" +
  "ACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBA" +
  "AgAAAgkAAAgkAAAgkAAAgED/A/HXYmfLNsqyAAAAAElFTkSuQmCC";

export function GET() {
  return new NextResponse(Buffer.from(DATA_BASE64, "base64"), {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
