// Sirve /logo.png con el logotipo de Factura Mis Gastos embebido.
// Solucion temporal libre de binarios: reemplazar por el archivo real en
// public/ cuando se pueda hacer push de binarios (ver PR #74).
import { NextResponse } from "next/server";

export const dynamic = "force-static";

const DATA_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIABAMAAAAGVsnJAAAAMFBMVEUlY+sAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAACTtglDAAAAEHRSTlP/AP8AAAAAAAAAAAAAAAAALNDuXQAACc1JREFUeNrtnUuWGzcMRUnEg2RG7UAn+1+T" +
  "j3ZQHCaTYiZxPm6pxA9AEk+vBkn72F0kLu6DPlXqjrfw2YcEAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiCADzm+" +
  "rVq45P/9MaZF+4gLLo0dL//mhg/gePsvbsAAjsp/d4ME8FPo32wroQE4mr/jhgTg6PquGwqAo/s7bwgAjqHvNt/eL79tNPqeHH/8" +
  "+atnA0bLn/CIYPpa4MgqFA+nEVBpv3kOZPP2m0tgBuDY+nTmEShZ+4xWMRAn9duc0wrAYbJXm0Eg+8ff9sT6M8BIVatBIJ7qtzi7" +
  "uKrf4Pziq379FcRZ/epriLf6tVcRd/UrryP+6tddSRzWr7qWeKxfczVxWb/ieloAJtcfQtkLwBGmH8dOABbUr7Wo7KTjithpACh5" +
  "DQCVdcVv/ToryyYmLsveOIAjLDyO9QBKWHrk1QBKXgtgeH3xOwB0DBTHA0BlC+J5AGhIKL4DMN4FcR6A4W2I9wCMiijeAzDaCXEf" +
  "gMGtiP8AjMko/gMw1g0BCMDQdgQhACNCCkIARjoiIAJ0t0RABOjuSR+AI2x4HPMAlLDlkacByHsCKLMAbCpAX2MER4C+zgiQAF2t" +
  "ESABunojSAL0NEeQBOjpTjOAI2x9HNYAStj8yMYA8u4Aii2A7QVobpGACdDcI0EToLVJgiZAa5f4g5TgEtDoqcAloLFPgidAW6ME" +
  "T4C2TgmgAE2tEkABmnoliAK0NEsQBWjplkAK0NAuPhOETECDsIKZgPqGCaYA9R0TUAGqWyagAlT3jI8CqAmotVZQE1DbNYEVoLJt" +
  "nAGwCagUV3ATUNc4wRWgrnOcAcAJqHJXgBNQ1TtBFqCmeZwByAmo0VegE1DRPkYAOgEVAgt2At43kBHATsB7hQU8AW9byAiAJ+Ct" +
  "xDQAfQS8s1jQE/Cui/yNk/oJ+N16z99bM5BoQCeAjFFj6QVQULqcGYE+ABmlyEIDugAUnCozDegBkHGqLDSgA0BBKjPTgHYAGanM" +
  "QgOaARSsOjMNaAWQseosNKARQEErNNOANgAZrdBCA5oAFLxKMw0ggAYAGa/SQgMaABTEUjMNIIBqABmx1EIDqgEUzFozDSCASgAZ" +
  "s9ZCAyoBFNRiMw0ggCoAGbXYQgMIoAZAwa020wACqACQcastNIAACOAtgIJc7tf59m3uBr4zAvsDyMjlFhpAAATwBkDBrjfTAAIg" +
  "gGsAGbveQgMIgAAuART0gjMNIAACIIALABm94EIDCIAACOA1gIJfcaYBBEAABEAArwBk/IoLDSAAAiAAAiAAAngKoHxCyZkGEAAB" +
  "EAABEMDfx+Sbpat/+cL5oAEEQADzAeRPKLnQAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAIgAAL4dADpE0qO" +
  "NIAAAADctU7k9Edqiny4AXc1BcRrcOWjAdz1poA4FUBt5+JVAC0FxKsAWluXi2eJuz8H6FQgeTdAVPcuXieA1hQQvwLobF4cC6Ci" +
  "gDgWQGX34lkADQXEswAa25erx0gH7wO0KxBdGyDqBovnCaAxBcS3ACE8PgrA13afHxUBAwF+PmfEFyD5NcBCAFcADCaAKwAmAngC" +
  "YCLAFwAJXYDo1gAbAfwAsJkAjgAYCeAGgJUAX04c0QVIPg0wE8ALAKsJ4AWAnQBfT52wBYguDTAUwAcAuwngA4ClAF9PHrEFSA4N" +
  "MBXAAwDLCeABgK0AT06fkAWI/gwwFmAPAPdlE+AZgPmPg1e3fisLkLY04OrWb2sBdgBwdeu39QTYAsD9YgqYC/AMQJouwMs+aAsQ" +
  "dzTgfvFAYC/AegBXt37bT4Cna8QFAjxXQF2AtJ8BV7d+zxBgOYD7RbsnTIDnANICAepuARwUIO5nwP2i4VMEWAzg6tbvKRPgOYC4" +
  "RID3N4IPC5B2M0DqfbAS4DmAtESAdx8GGRYg7jYDpOUxwUiApQDuTc8KzjAPwKQp+Gh6XjguQNrNgLPllcEZJhowawo+Gl4bjgsQ" +
  "93sidNa/O2AlwOJngi8UmPYQ8BJAXKuAjQBpx5fDTxWYKcArAGmlAjYCxB1nwFMFpgqwHMBZ8wTxDNMBxIUKGAmQ9jSgpruWArwE" +
  "kDZSQEWAuOkMqOivqQAvAUy8OvKYIcBLpTe4OnyuFOA1gLSLAjoCxLCvAdc9NhbgNYCZl0gf5gK8FnqLu8TOdQJcAEhbKKAkQAxb" +
  "G/C6z+YCXACYep/Ew1aAC503uVX2XCXAFYC0XgEtAWLY3YDnvZ4gwBWAuTdLPQwFuJJ5m9vlzzUCXAJIaxR4qAsQgwMD/un3ec4U" +
  "4BLA5E8OPH7876EswKXKErbJwPnjv6eyADG4iMDfLX/894sJx7egnoHvIwqc//vCPgF7fWrs8aPvj2kCvAEwdwiE80ffT00Brj2O" +
  "t8u/PuYSkPPnLxSOW3ATgX/7fs5jHnbKgMURgyMDFhwyhM/DkcYMSOAJYAQkgGcgjRqQsBPACEjAzkAaNyBBJ4ARkACdgaRhQEJO" +
  "QA2AiCwAZ4AE4AxEJQAROAF1EUi4AnAGSMDNQNIzIMEmoBJAhBWAM0ACagaiKoCImoDqCCRQAaoBRFAB6odgwhSAjwISMDOQ9A1I" +
  "kAloABAhBWiZAQlRgBYAEVGApkeBBChAE4AIKEDb84CEJ0AbgIgnAJ8JSoDLQDQEEOES0BqBhCZAK4CIJkDzEExgAjQDiGACtD8M" +
  "3vauv3l7Yo546wD0AIhIAeh6JpiQBOgBEJEE6HotkIAE6AIQgQToezWYcAToAxBxBOh8P2DLZ0N9m5KJsDcMQDeACBKA/rfEEogA" +
  "3QAiiAD9b4puNge7tyPTkW8VgBEAESEAQ9cFbgABGLswkvwHYAxA9B+AwUtjN/cBGL02mLwHYBRA9B6A4avDN+cBGL88nnwHYBxA" +
  "XExgeH1Z3YHVBsrqDK5eXDZowlL9ZIMYLl1Zgl8CKuvKJiYuy57ObXJLBqHOohK8ElBaUnbScUXstADMHoRq60lwSUBvNQkeCSiu" +
  "JcEhAc2VJPgjoLqOBHcEdFeR4I2A8hoSnBHQXkGCLwLq55fgioD+2fU/MxQNXxfc9OlafGjKjIDFicVJo8zUEidRNRsuRp8b1O+W" +
  "jVWGH5y87R9/WwCqLTN8ZDH86Kzerq30NwagtfFo+oZjNH47s+TNn1tbf3p8FPAtbb7BmqP/d/VM2Fyc8o7+sWv5swD0IJi0sTjt" +
  "mk7TOJz4BuvMi1rHXs2fD6CKweQNxQWXNY9dil8F4NlIWHabSdz85wGYH/w5QgRAAARAAARAAARAAARAAARAAARAAARAAARAAARA" +
  "AARAAATwMcdf2jnTGdTtWmIAAAAASUVORK5CYII=";

export function GET() {
  return new NextResponse(Buffer.from(DATA_BASE64, "base64"), {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
